import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "@mui/material/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/">Lumini's Blog!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <h2>Contact Me</h2>

        <div className={styles.grid}>
          <a href="https://www.linkedin.com/feed/" className={styles.card}>
            <h2>LinkedIn</h2>
          </a>

          <a href="https://www.facebook.com/" className={styles.card}>
            <h2>Facebook</h2>
          </a>

          <a href="https://github.com/" className={styles.card}>
            <h2>GitHub</h2>
          </a>

          <a href="https://twitter.com/?lang=en" className={styles.card}>
            <h2>Twitter</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <Button variant="contained">Contained</Button>
      </footer>
    </div>
  );
}
